### PR TITLE
add catppuccin theme

### PR DESCRIPTION
**Pull request by MoritzBoehme**
Hi,
this adds the catppuccin theme. I wanted to use this myself and thought maybe others would enjoy it as well.

### CODE REVIEW

**Comment by jordanisaacs** [comment]
Thanks for the PR, sorry you got caught in the middle of a large refactor that I just finished. Three comments but otherwise looks good.

1. Add the plugin to the [plugins.adoc](https://github.com/jordanisaacs/neovim-flake/blob/main/docs/plugins.adoc#themes) file instead of the readme.
2. Add "catpuccin" to the [availablePlugins](https://github.com/jordanisaacs/neovim-flake/blob/main/modules/lib/types-plugin.nix). It does not exist in `flake.nix` anymore.
3. Add a changelog (feel free to link to your github) at: https://github.com/jordanisaacs/neovim-flake/blob/main/docs/release-notes/rl-0.1.adoc

**Comment by MoritzBoehme** [comment]
The restructure looks awesome. I'll try to fix up this PR today and will let you know when I am done.

**Comment by MoritzBoehme** [comment]
Should now be working again :)

**Comment by jordanisaacs** [comment]
Thanks for the addition!

**Pull request merged**
